modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/CAS-ual-TY/Spells-And-Shields/issues"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="https://github.com/CAS-ual-TY/Spells-And-Shields"
    logoFile="logo.png"
    credits="Mojang and the NeoForged Team"
    authors="CAS_ual_TY"
    description='''Vanilla+ style magic extension that adds mana and spell trees. Fully data driven.'''

[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[${neo_version},)" #mandatory
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

