modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
issueTrackerURL="https://github.com/CAS-ual-TY/Spells-And-Shields/issues"

[[mods]]
    modId="spells_and_shields"
    version="${file.jarVersion}"
    displayName="Spells and Shields"
    displayURL="https://github.com/CAS-ual-TY/Spells-And-Shields"
    logoFile="logo.png"
    credits="Mojang and the Minecraft Forge Team"
    authors="CAS_ual_TY"
    description='''Vanilla+ style magic extension that adds mana and spell trees. Highly configurable.'''
